{
 "title": "kafka监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": "SHOW TAG VALUES FROM burrow_group WITH KEY = \"cluster\""
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Lag监控",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "burrow_group",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Lag Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "burrow_partition",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Topic Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "burrow_topic",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}