{
 "title": "Prometheus 主机监控",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "label_values(up,job)" }
  ]
 },
 "panels": [
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_uptime{job =~ \"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_n_cpus{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mem_total{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "disk_total{job=~\"$host\",device=\"rootfs\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mem_used_percent{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cpu_usage_user{job=~\"$host\",cpu=\"cpu-total\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "processes_total{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Load -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{job =~ \"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1 min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "system_load5{job =~ \"$host\"}",
     "legendFormat": "5 min"
    },
    {
     "expr": "system_load15{job =~ \"$host\"}",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Network -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{job=\"$host\"}[10s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{interface}} recv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(net_bytes_sent{job=\"$host\"}[10s])",
     "legendFormat": "{{interface}} sent"
    }
   ]
  },
  {
   "title": "I/O -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{job=\"$host\"}[10s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_iowait{job=~\"$host\",cpu=\"cpu-total\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "iowait",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "cpu_usage_steal{job=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "cpu_usage_system{job=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{job=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "user"
    },
    {
     "expr": "cpu_usage_irq{job=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "cpu_usage_guest{job=~\"$host\",cpu=\"cpu-total\"}",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Mem -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_cached{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cache",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "mem_total{job=~\"$host\"}",
     "legendFormat": "total"
    },
    {
     "expr": "mem_buffered{job=~\"$host\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_used{job=~\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_slab{job=~\"$host\"}",
     "legendFormat": "slab"
    },
    {
     "expr": "mem_used_percent{job=~\"$host\"}",
     "legendFormat": "used_percent"
    }
   ]
  },
  {
   "title": "Disk -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{job=~\"$host\",device=\"rootfs\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "disk_used{job=~\"$host\",device=\"rootfs\"}",
     "legendFormat": "used"
    },
    {
     "expr": "disk_used_percent{job=~\"$host\",device=\"rootfs\"}",
     "legendFormat": "used_percent"
    }
   ]
  },
  {
   "title": "Per CPU -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{job=~\"$host\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Swap -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "swap_total{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "swap_used{job=~\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "swap_used_percent{job=~\"$host\"}",
     "legendFormat": "used_percent"
    }
   ]
  },
  {
   "title": "Proccessing -> $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "processes_dead{job=~\"$host\"}",
     "legendFormat": "dead"
    },
    {
     "expr": "processes_idle{job=~\"$host\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "processes_paging{job=~\"$host\"}",
     "legendFormat": "paging"
    },
    {
     "expr": "processes_running{job=~\"$host\"}",
     "legendFormat": "running"
    },
    {
     "expr": "processes_sleeping{job=~\"$host\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "processes_stopped{job=~\"$host\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "processes_zombies{job=~\"$host\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Network  Detail -> $host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_err_in{job=~\"$host\"}[10s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{interface}} err_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(net_err_out{job=~\"$host\"}[10s])",
     "legendFormat": "{{interface}} err_out"
    },
    {
     "expr": "rate(net_drop_in{job=~\"$host\"}[10s])",
     "legendFormat": "{{interface}} drop_in"
    },
    {
     "expr": "rate(net_drop_out{job=~\"$host\"}[10s])",
     "legendFormat": "{{interface}} drop_out"
    },
    {
     "expr": "rate(net_packets_recv{job=~\"$host\"}[10m])",
     "legendFormat": "{{interface}} packets_recv"
    },
    {
     "expr": "rate(net_packets_sent{job=~\"$host\"}[10m])",
     "legendFormat": "{{interface}} packets_sent"
    }
   ]
  },
  {
   "title": "netstat -> $host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netstat_tcp_close{job=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "close",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "netstat_tcp_close_wait{job=~\"$host\"}",
     "legendFormat": "close_wait"
    },
    {
     "expr": "netstat_tcp_listen{job=~\"$host\"}",
     "legendFormat": "tcp_listen"
    },
    {
     "expr": "netstat_tcp_syn_recv{job=~\"$host\"}",
     "legendFormat": "syn_recv"
    },
    {
     "expr": "netstat_tcp_time_wait{job=~\"$host\"}",
     "legendFormat": "time_wait"
    },
    {
     "expr": "netstat_tcp_established{job=~\"$host\"}",
     "legendFormat": "established"
    },
    {
     "expr": "netstat_udp_socket{job=~\"$host\"}",
     "legendFormat": "udp_socket"
    },
    {
     "expr": "netstat_tcp_closing{job=~\"$host\"}",
     "legendFormat": "closing"
    },
    {
     "expr": "netstat_tcp_fin_wait1{job=~\"$host\"}",
     "legendFormat": "fin_wait1"
    },
    {
     "expr": "netstat_tcp_fin_wait2{job=~\"$host\"}",
     "legendFormat": "fin_wait2"
    },
    {
     "expr": "netstat_tcp_syn_sent{job=~\"$host\"}",
     "legendFormat": "syn_sent"
    }
   ]
  }
 ]
}