{
 "title": "Prometheus memcache监控",
 "description": "Monitors Kubernetes Memcached Pods. Shows memory usage, hit rate, evicts and reclaims rate, items in cache, network stats, commands rate. Requires Memcached Exporter for Prometheus.",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(memcached_up, job)"
   },
   {
    "name": "dbname",
    "query": "label_values(memcached_up, dbname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{job=~\"$host\",dbname=~\"$dbname\"}) / sum(memcached_limit_bytes{job=~\"$host\",dbname=~\"$dbname\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{status=\"hit\",command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}[5m])) / sum (irate (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}[5m]\n))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(memcached_items_evicted_total{job=~\"$host\",dbname=~\"$dbname\"}[50m])",
     "legendFormat": "evicts"
    },
    {
     "expr": "irate(memcached_items_reclaimed_total{job=~\"$host\",dbname=~\"$dbname\"}[50m])",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_current_bytes{job=~\"$host\",dbname=~\"$dbname\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_limit_bytes{job=~\"$host\",dbname=~\"$dbname\"})"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{status=\"hit\",command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}) / sum (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum (memcached_commands_total{status=\"miss\",command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}) / sum (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{job=~\"$host\",dbname=~\"$dbname\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{job=~\"$host\",dbname=~\"$dbname\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{job=~\"$host\",dbname=~\"$dbname\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_read_bytes_total{job=~\"$host\",dbname=~\"$dbname\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (irate (memcached_written_bytes_total{job=~\"$host\",dbname=~\"$dbname\"}[5m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{job=~\"$host\",dbname=~\"$dbname\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}) / (sum (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}) + sum (memcached_commands_total{command=\"set\",job=~\"$host\",dbname=~\"$dbname\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum (memcached_commands_total{command=\"set\",job=~\"$host\",dbname=~\"$dbname\"})  / (sum (memcached_commands_total{command=\"get\",job=~\"$host\",dbname=~\"$dbname\"}) + sum (memcached_commands_total{command=\"set\",job=~\"$host\",dbname=~\"$dbname\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate (memcached_commands_total{job=~\"$host\",dbname=~\"$dbname\"}[5m])",
     "legendFormat": "{{command}} {{status}}"
    }
   ]
  }
 ]
}